name: Automated Build
on:
push:
branches:
- main
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout Repository
uses: yapck-wm23-bit/elearningt
- name: Build Project
run: echo "Building the project..."
